spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        default_batch_fetch_size: 100

logging:
  level:
    org:
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql: ERROR