spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    show-sql: false

logging:
  level:
    org:
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql: ERROR